service: iidx-lambda
provider:
  name: aws
  runtime: nodejs12.x
custom:
  functionsBasePath: src
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      packagePath: 'package.json'
    packager: 'npm'
  serverless-offline:
    host: '0.0.0.0'
plugins:
  - serverless-functions-base-path
  - serverless-webpack
  - serverless-offline
functions:
  helloWorld:
    handler: hello/hello.handler
    events:
      - http: GET hello
  iidx:
    handler: iidxCapture/iidxCapture.handler
    events:
      - http: GET iidx
      - http: POST iidx
